services:

  customer-api:
    build: .
    container_name: customer-api

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env

    volumes:
      - .:/app

    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  postgres:
    image: postgres:16
    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M


volumes:
  postgres_data:
